import type { Metadata } from "next";
import localFont from "next/font/local";
import { Open_Sans } from "next/font/google";
import "./globals.css";
import Navbar from "../components/section/Navbar";
import Footer from "../components/section/Footer";
import CursorFollower from "../components/ui/CursorFollower";
import LenisProvider from "../components/providers/LenisProvider";

const karigaar = localFont({
  src: [
    {
      path: "../../public/fonts/karigaarSans-semibold.ttf",
      weight: "200",
      style: "normal",
    },
    {
      path: "../../public/fonts/karigaarSans-bold.ttf",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-karigaar",
  display: "swap",
});

const openSans = Open_Sans({
  subsets: ["latin"],
  weight: ["400", "500", "600"],
  variable: "--font-sans",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${karigaar.variable} ${openSans.variable} h-full antialiased`}
    >
      <body className={`${karigaar.className} min-h-full flex flex-col`}>
        <LenisProvider>
          <CursorFollower />
          <Navbar />
          <main className="flex-1">{children}</main>
          <Footer />
        </LenisProvider>
      </body>
    </html>
  );
}
